repository_type: pipeline
lint:
  files_exist:
  - CODE_OF_CONDUCT.md
  - assets/nf-core-pocpbenchmark_logo_light.png
  - docs/images/nf-core-pocpbenchmark_logo_light.png
  - docs/images/nf-core-pocpbenchmark_logo_dark.png
  - .github/ISSUE_TEMPLATE/config.yml
  - .github/workflows/awstest.yml
  - .github/workflows/awsfulltest.yml
  - .github/workflows/branch.yml
  - .github/workflows/ci.yml
  - .github/workflows/linting_comment.yml
  - .github/workflows/linting.yml
  - conf/igenomes.config
  nextflow_config:
  - manifest.name
  - manifest.homePage
  multiqc_config:
  - report_comment
  readme:
  - nextflow_badge
  pipeline_name_conventions: False
  actions_awsfulltest: False
